nginx-ingress:
  podSecurityPolicy:
    enabled: true
  rbac:
    create: true
  serviceAccount:
    create: true
  controller:
    replicaCount: 3
    service:
      loadBalancerIP: '${taito_zone_default_ip}'
      externalTrafficPolicy: Local
    extraArgs:
      annotations-prefix: ingress.kubernetes.io
      # enable-dynamic-configuration: true
