nginx-ingress:
  rbac:
    create: true
  serviceAccount:
    create: true
  controller:
    replicaCount: 3
    service:
      loadBalancerIP: '${zone_ingress_ip}'
    extraArgs:
      annotations-prefix: ingress.kubernetes.io
      # enable-dynamic-configuration: true
