apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: {{ .Chart.Name }}
          image: tecnativa/tcp-proxy:latest
          resources:
            requests:
              cpu: 2m
              memory: 5Mi
            limits:
              cpu: 100m
              memory: 256Mi
          ports:
          {{- range .Values.forwards }}
            - containerPort: {{ .containerPort }}
          {{- end }}
          env:
            - name: TIMEOUT_CLIENT
              value: {{ .Values.timeoutClient }}
            - name: TIMEOUT_CLIENT_FIN
              value: {{ .Values.timeoutClientFin }}
            - name: TIMEOUT_CONNECT
              value: {{ .Values.timeoutConnect }}
            - name: TIMEOUT_SERVER
              value: {{ .Values.timeoutServer }}
            - name: TIMEOUT_SERVER_FIN
              value: {{ .Values.timeoutServerFin }}
            - name: TIMEOUT_TUNNEL
              value: {{ .Values.timeoutTunnel }}
            - name: PRE_RESOLVE
              value: {{ .Values.preResolve | quote }}
            - name: LISTEN
              value: {{ range .Values.forwards }}:{{ .containerPort }} {{ end }}
            - name: TALK
              value: {{ range .Values.forwards }}{{ .talk }} {{ end }}
